/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import OBJ.KhachHang;
import OBJ.SanPham;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lovan
 */
public class frmSanPham extends javax.swing.JPanel {

    /**
     * Creates new form frmSanPham
     */
    private DefaultTableModel defaultTableModel;
    SanPham sp = new SanPham();
    ArrayList<SanPham> listSP = new ArrayList<>();

    public frmSanPham() {
        initComponents();
        loadFile();
        getData(listSP);

    }

    public void loadFile() {
        try {
            BufferedReader br = null;
            FileReader fr = null;
            listSP = new ArrayList<>(); //lưu ý
            fr = new FileReader("sanpham.txt");
            br = new BufferedReader(fr);
            String s = null;

            try {
                while ((s = br.readLine()) != null) {
                    //Cắt chuỗi:
                    String arr[] = s.split("\t");
                    //Khởi tạo
                    SanPham sp = new SanPham();
                    sp.setMaSanPham(arr[0]);
                    sp.setTenSP(arr[1]);
                    sp.setDonViTinh(arr[2]);
                    sp.setTenNSX(arr[3]);
                    sp.setGiaBan((arr[4]));
                    sp.setGiaNhap((arr[5]));
                    sp.setSoLuong((arr[6]));
                    listSP.add(sp);
                }
            } catch (IOException ex) {
                Logger.getLogger(frmNhanVienTemplate.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmNhanVienTemplate.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void saveFile() {

        try {
            BufferedWriter bw = null; //Khởi tạo
            FileWriter fw = null; //Khởi tạo
            String data = ""; //Tạo một string data bằng rỗng.
            for (int i = 0; i < listSP.size(); i++) {
                String row = ""; //tạo hàng rỗng
                row = row + listSP.get(i).getMaSanPham() + "\t";
                row = row + listSP.get(i).getTenSP() + "\t";
                row = row + listSP.get(i).getDonViTinh() + "\t";
                row = row + listSP.get(i).getTenNSX() + "\t";
                row = row + listSP.get(i).getGiaBan() + "\t";
                row = row + listSP.get(i).getGiaNhap() + "\t";
                row = row + listSP.get(i).getSoLuong() + "\n";
                data += row;
            }
            fw = new FileWriter("sanpham.txt");
            bw = new BufferedWriter(fw);
            bw.write(data);
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(frmNhanVienTemplate.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void getData(ArrayList<SanPham> listSP) {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Mã SP");
        defaultTableModel.addColumn("Tên SP");
        defaultTableModel.addColumn("Đơn vị tính");
        defaultTableModel.addColumn("Tên NSX");
        defaultTableModel.addColumn("Giá bán");
        defaultTableModel.addColumn("Giá nhập");
        defaultTableModel.addColumn("Số lượng");

        for (SanPham obj : listSP) {
            Vector vector = new Vector();
            vector.add(obj.getMaSanPham());
            vector.add(obj.getTenSP());
            vector.add(obj.getDonViTinh());
            vector.add(obj.getTenNSX());
            vector.add(obj.getGiaBan());
            vector.add(obj.getGiaNhap());
            vector.add(obj.getSoLuong());
            defaultTableModel.addRow(vector);
        }
        bangsanpham.setModel(defaultTableModel);
    }
    
    public void reset (){
        txt_maSanPham.setText("");
        txt_tenSP.setText("");
        txt_tenNSX.setText("");
        txt_donViTinh.setText("");
        txt_giaNhap.setText("");
        txt_giaBan.setText("");
        txt_soLuong.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangsanpham = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_maSanPham = new javax.swing.JTextField();
        txt_donViTinh = new javax.swing.JTextField();
        txt_giaNhap = new javax.swing.JTextField();
        txt_soLuong = new javax.swing.JTextField();
        txt_tenSP = new javax.swing.JTextField();
        txt_tenNSX = new javax.swing.JTextField();
        txt_giaBan = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txt_timKiem = new javax.swing.JTextField();
        timKiem = new javax.swing.JButton();
        them = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        sua = new javax.swing.JButton();
        thoat = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        bangsanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bangsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangsanphamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bangsanpham);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 328, 1000, 140);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 102));
        jLabel1.setText("Zent Coding School");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(65, 20, 124, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quản lý sản phẩm");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(479, 11, 207, 29);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Xin chào, Nam Đẹp Trai !");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(39, 57, 202, 22);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Mã sản phẩm");

        jLabel5.setText("Đơn vị tính");

        jLabel6.setText("Giá nhập");

        jLabel7.setText("Số lượng");

        jLabel8.setText("Tên SP");

        jLabel9.setText("Tên NSX");

        jLabel10.setText("Giá bán");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Thông tin sản phẩm");

        txt_maSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maSanPhamActionPerformed(evt);
            }
        });

        txt_donViTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_donViTinhActionPerformed(evt);
            }
        });

        txt_tenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenSPActionPerformed(evt);
            }
        });

        txt_tenNSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenNSXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_maSanPham)
                            .addComponent(txt_donViTinh)
                            .addComponent(txt_soLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(txt_giaNhap))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_tenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_tenNSX)
                                    .addComponent(txt_giaBan))))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(txt_maSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(txt_donViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tenNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(txt_giaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_giaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(39, 97, 555, 213);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Tìm kiếm");

        timKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Magnifier-icon.png"))); // NOI18N
        timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timKiem))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(657, 97, 279, 93);

        them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/more.png"))); // NOI18N
        them.setText("Thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });
        jPanel1.add(them);
        them.setBounds(679, 208, 87, 33);

        xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        xoa.setText("Xóa");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });
        jPanel1.add(xoa);
        xoa.setBounds(823, 208, 89, 33);

        sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wrench.png"))); // NOI18N
        sua.setText("Sửa");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });
        jPanel1.add(sua);
        sua.setBounds(679, 277, 87, 33);

        thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/turn-on.png"))); // NOI18N
        thoat.setText("Thoát");
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });
        jPanel1.add(thoat);
        thoat.setBounds(823, 277, 89, 33);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hinh-nen-full-hd-cho-laptop-3.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 0, 1000, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_maSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maSanPhamActionPerformed

    private void txt_donViTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_donViTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_donViTinhActionPerformed

    private void timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiemActionPerformed
        String tuKhoa = txt_timKiem.getText();
        if(tuKhoa == ""){
            getData(listSP);
        }
        else {
            ArrayList<SanPham> listSP_timKiem = new ArrayList<>();
            for (int i = 0; i < listSP.size(); i++) {
                if (listSP.get(i).getMaSanPham().contains(tuKhoa)){
                    listSP_timKiem.add(listSP.get(i));
                }
            }
            getData(listSP_timKiem);
        }
    }//GEN-LAST:event_timKiemActionPerformed

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        String maSP = txt_maSanPham.getText();
        String tenSP = txt_tenSP.getText();
        String tenNSX = txt_tenNSX.getText();
        String donViTinh = txt_donViTinh.getText();
        String giaNhap = txt_giaNhap.getText();
        String giaBan = txt_giaBan.getText();
        String soLuong = txt_soLuong.getText();

        SanPham sp = new SanPham();
        if (maSP.equals("")) {
            JOptionPane.showMessageDialog(this, "Mã sản phẩm không được để trống !");
            return;
        }
        for (int i = 0; i < listSP.size(); i++) {
            if (maSP.equals(listSP.get(i).getMaSanPham())) {
                JOptionPane.showMessageDialog(this, "Mã bị trùng, hãy nhập lại");
                return;
            } else {
                sp.setMaSanPham(maSP);
            }
        }
        if (tenSP.equals("")) {
            JOptionPane.showMessageDialog(this, "Tên sản phẩm không được để trống !");
            return;
        }
        sp.setTenSP(tenSP);
        if (tenNSX.equals("")) {
            JOptionPane.showMessageDialog(this, "Tên nhà sản xuất không được để trống !");
            return;
        }
        sp.setTenNSX(tenNSX);
        if (donViTinh.equals("")) {
            JOptionPane.showMessageDialog(this, "Đơn vị tính không được để trống !");
            return;
        }
        sp.setDonViTinh(donViTinh);
        if (giaNhap.equals("")) {
            JOptionPane.showMessageDialog(this, "Giá nhập không được để trống !");
            return;
        }
        if (giaNhap.equals("0")) {
            JOptionPane.showMessageDialog(this, "Giá nhập không có giá trị !");
            return;
        }
        sp.setGiaNhap(giaNhap);
        if (giaBan.equals("")) {
            JOptionPane.showMessageDialog(this, "Giá bán không được để trống !");
            return;
        }
        if (giaBan.equals("0")) {
            JOptionPane.showMessageDialog(this, "Giá bán không có giá trị !");
            return;
        }
        sp.setGiaBan(giaBan);
        if (soLuong.equals("")) {
            JOptionPane.showMessageDialog(this, "Số lượng không được để trống !");
            return;
        }
        if (soLuong.equals("0")) {
            JOptionPane.showMessageDialog(this, "Số lượng không có giá trị !");
            return;
        }
        sp.setSoLuong(soLuong);

        listSP.add(sp);
        getData(listSP);
        saveFile();
        JOptionPane.showMessageDialog(this, "Thêm mới thành công !");
        reset();
    }//GEN-LAST:event_themActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa sản phẩm " + sp.getMaSanPham()+ " không ?", "Xóa sản phẩm", 2);
        if (confirm == JOptionPane.YES_OPTION) {
            if (listSP.remove(sp) == true) {
                saveFile();
                JOptionPane.showConfirmDialog(this, "Xóa thành công !");
                getData(listSP);
                reset();
            } else {
                JOptionPane.showConfirmDialog(this, "Xóa thất bại !");
            }
        }
    }//GEN-LAST:event_xoaActionPerformed

    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_thoatActionPerformed

    private void txt_tenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenSPActionPerformed

    private void txt_tenNSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenNSXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenNSXActionPerformed

    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        String maSP = txt_maSanPham.getText();
        String tenSP = txt_tenSP.getText();
        String tenNSX = txt_tenNSX.getText();
        String donViTinh = txt_donViTinh.getText();
        String giaNhap = txt_giaNhap.getText();
        String giaBan = txt_giaBan.getText();
        String soLuong = txt_soLuong.getText();

        SanPham sp = new SanPham();
        sp.setMaSanPham(maSP);
        if (tenSP.equals("")) {
            JOptionPane.showMessageDialog(this, "Tên sản phẩm không được để trống !");
            return;
        }
        sp.setTenSP(tenSP);
        if (tenNSX.equals("")) {
            JOptionPane.showMessageDialog(this, "Tên nhà sản xuất không được để trống !");
            return;
        }
        sp.setTenNSX(tenNSX);
        if (donViTinh.equals("")) {
            JOptionPane.showMessageDialog(this, "Đơn vị tính không được để trống !");
            return;
        }
        sp.setDonViTinh(donViTinh);
        if (giaNhap.equals("")) {
            JOptionPane.showMessageDialog(this, "Giá nhập không được để trống !");
            return;
        }
        if (giaNhap.equals("0")) {
            JOptionPane.showMessageDialog(this, "Giá nhập không có giá trị !");
            return;
        }
        sp.setGiaNhap(giaNhap);
        if (giaBan.equals("")) {
            JOptionPane.showMessageDialog(this, "Giá bán không được để trống !");
            return;
        }
        if (giaBan.equals("0")) {
            JOptionPane.showMessageDialog(this, "Giá bán không có giá trị !");
            return;
        }
        sp.setGiaBan(giaBan);
        if (soLuong.equals("")) {
            JOptionPane.showMessageDialog(this, "Số lượng không được để trống !");
            return;
        }
        if (soLuong.equals("0")) {
            JOptionPane.showMessageDialog(this, "Số lượng không có giá trị !");
            return;
        }
        sp.setSoLuong(soLuong);

        listSP.set(index, sp);
        getData(listSP);
        saveFile();
        JOptionPane.showMessageDialog(this, "Chỉnh sửa thành công " + sp.getMaSanPham());
        reset();
    }//GEN-LAST:event_suaActionPerformed
    int index;
    private void bangsanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangsanphamMouseClicked
        sua.setEnabled(true);
        xoa.setEnabled(true);
        // lấy ra bản ghi
        int row = bangsanpham.getSelectedRow();
        String maSP = bangsanpham.getValueAt(row, 0).toString();
        for (int i = 0; i < listSP.size(); i++) {
            if (maSP.equals(listSP.get(i).getMaSanPham())) {
                sp = listSP.get(i);
                index = i;
                break;
            }
        }
        txt_maSanPham.setEnabled(false);
        them.setEnabled(false);
        
        txt_maSanPham.setText(sp.getMaSanPham());
        txt_tenNSX.setText(sp.getTenNSX());
        txt_tenSP.setText(sp.getTenSP());
        txt_soLuong.setText(sp.getSoLuong());
        txt_donViTinh.setText(sp.getDonViTinh());
        txt_giaBan.setText(sp.getGiaBan());
        txt_giaNhap.setText(sp.getGiaNhap());
    }//GEN-LAST:event_bangsanphamMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangsanpham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sua;
    private javax.swing.JButton them;
    private javax.swing.JButton thoat;
    private javax.swing.JButton timKiem;
    private javax.swing.JTextField txt_donViTinh;
    private javax.swing.JTextField txt_giaBan;
    private javax.swing.JTextField txt_giaNhap;
    private javax.swing.JTextField txt_maSanPham;
    private javax.swing.JTextField txt_soLuong;
    private javax.swing.JTextField txt_tenNSX;
    private javax.swing.JTextField txt_tenSP;
    private javax.swing.JTextField txt_timKiem;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables
}
